name: TIME TO BUILD...
on: 
  #releasepush:
    #pushbuild
  watch: 
      types: [started]
#######################   CHANGE ONLY ROM_URL,ROM_NAME,FIRMWAREZIPANEM,ZIPNAME,SCRIPT_NAME  ###################################
env:
  ROM_URL: https://dl.google.com/developers/android/sc/images/ota/blueline-ota-spp1.210122.020.a3-eba1062e.zip
  ROM_NAME: Pixel
  FIRMWAREZIPNAME: blueline-ota-spp1.210122.020.a3-eba1062e.zip
  ZIP_NAME: Pixel-4a-@PriyoGSI-19-02-2021
  SCRIPT_NAME: PIXELDP
  TZ: Asia/Bangladesh
  SFDIRA1: cd /home/pfs/project/priyogsis/PriyoFiles
  SFDIRA2: cd /home/pfs/project/priyogsis/PriyoDumps
  SFUSER: ${{ secrets.SFUSER }}
  SECRETS_PASSWORD: ${{ secrets.SFPASS }}
  
jobs:
    build:
       runs-on: ubuntu-latest
    
    
       steps:
        - name: Checkout
          uses: actions/checkout@main
       
           
        - name: Setting up the SPICES and its SPICES
          run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt-get install -y expect
            git clone "https://github.com/Priiiyo/PGTools-ErfanGSIs" ErfanGSIs
            sudo chmod -R 777 ErfanGSIs
            cd ErfanGSIs
            sudo bash setup.sh 
            
        - name: DOWNLOADING THE FIRMWARE
          run: cd ErfanGSIs && sudo wget $ROM_URL 
          
        - name: GENERATION OF BAKED GOODIES
          run: | 
            cd ErfanGSIs && sudo ./$SCRIPT_NAME.sh $ROM_NAME $FIRMWAREZIPNAME && sudo umount system && sudo rm -rf system
            
            
        - name: MOUNTING THE SYSTEM
          run: cd ErfanGSIs/cache && sudo mkdir dynamic && sudo mount -o ro system.img dynamic 
         
        - name: MAKING THE COOKIES
          run: cd ErfanGSIs && sudo ./url2GSI.sh cache/dynamic $ROM_NAME  
       
        - name: Zipping BOTH COOKIES
          run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img 
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
        - name: uploading to PRIYOFILES
          run: |   
              cd ErfanGSIs/output
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"${{ secrets.SFDIRA2 }}\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"${{ secrets.SFDIRA1 }}\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"${{ secrets.SFDIRA1 }}\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"  
