name: Time to Bake...
on: push
#######################   CHANGE ONLY TG_NAME,ROM_URL,ROM_NAME,FIRMWAREZIPANEM,ZIPNAME,SCRIPT_NAME  ###################################
env:
  TG_NAME: "OnePlus Nord"
  ROM_URL: https://otafsg1.h2os.com/patch/amazone2/GLO/NordOxygen/NordOxygen_14.O.11_GLO_011_2010232026/NordOxygen_14.O.11_OTA_011_all_2010232026_83bb980e97.zip
  ROM_NAME: OxygenOS
  FIRMWAREZIPNAME: NordOxygen_14.O.11_OTA_011_all_2010232026_83bb980e97.zip
  ZIP_NAME: OXYGENOSNORDLATEST-AMY-28-10
  SCRIPT_NAME: OOSDP
  TZ: Europe/London
  MIR: wet
  SFDIRA1: cd /home/pfs/project/amyGSI/
  SFDIRA2: cd /home/pfs/project/amyGSI
  SFUSER: ${{ secrets.SFUSER }}
  SECRETS_PASSWORD: ${{ secrets.SFGPASS }}
  
jobs:
    build:
       runs-on: ubuntu-latest
    
    
       steps:
        - name: Checkout
          uses: actions/checkout@main
       
           
        - name: Setting up the SPICES and its SPICES
          run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt-get install -y expect
            git clone "https://github.com/amyGSI/AmyBakerTools" ErfanGSIs
            sudo chmod -R 777 ErfanGSIs
            cd ErfanGSIs
            sudo bash setup.sh 
            
        - name: DOWNLOADING THE FIRMWARE
          run: cd ErfanGSIs && sudo wget $ROM_URL 
          
        - name: GENERATION OF BAKED GOODIES
          run: | 
            cd ErfanGSIs && sudo ./$SCRIPT_NAME.sh $ROM_NAME $FIRMWAREZIPNAME && sudo umount system && sudo rm -rf system
            
            
        - name: MOUNTING THE SYSTEM
          run: cd ErfanGSIs/cache && sudo mkdir dynamic && sudo mount -o ro system.img dynamic 
         
        - name: MAKING THE COOKIES
          run: cd ErfanGSIs && sudo ./url2GSI.sh cache/dynamic $ROM_NAME  
       
        - name: Zipping BOTH COOKIES
          run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img 
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
        - name: Uploading to AMYBAKERY
          run: |   
              cd ErfanGSIs/output
              expect -c " 
              spawn sftp amygsi@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA2\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp amygsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp amygsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
